# 网关微服务：服务路由，请求的过滤

server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5  # 拉取服务的间隔时间
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/**  # 路由到商品的微服务
    search-service: /search/**  # 路由到搜索微服务
    user-service: /user/**  # 用户微服务
    auth-service: /auth/**  # 授权中心微服务
    cart-service: /cart/**  # 购物车微服务
    order-service: /order/**  # 下单微服务
  add-host-header: true  # 网关转发时携带域名信息
  sensitive-headers:    # 覆盖默认敏感头信息为空就可以（zuul网关默认拦截敏感头信息）
ribbon:
  ReadTimeout: 20000  # 通信超时
leyou:  # 用于解析token，并进行拦截
  jwt:
    pubKeyPath: H:\\JavaTmpFile\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
