server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false  # 开发时建议关闭缓存
  rabbitmq:  # 消息队列配置,消费方
    host: 192.168.76.128
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5  # 拉取服务的时间