server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.76.128
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:  # 短信模板必须字段
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:   # 你自己的AccessKeySecret
    signName: 乐优商城  # 签名名称
    verifyCodeTemplate: SMS_171853386  # 模板名称
