server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:  # 配置redis服务的地址
    host: 192.168.76.128
  rabbitmq:
    host: 192.168.76.128
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: org.junhi.user.pojo